### ISSUE TITLE
Can't locate object method "squish"

### ISSUE THREAD

**Issue by eserte** [jberger/Galileo#51]
My smokers report test failures, probably (again) with Mojolicious 7.

A sample report: http://www.cpantesters.org/cpan/report/f2ba2fbe-4e01-11e6-babd-99c5dbe93021

**Comment by eserte** [comment]
Probably this change is relevant: https://metacpan.org/source/SRI/Mojolicious-7.0/Changes#L6

**Comment by jberger** [comment]
Thank you!
