### ISSUE TITLE
error with configure

### ISSUE THREAD

**Issue by Bel-Kin** [jberger/Galileo#52]
new installation
1. bin/galileo setup
2. http://127.0.0.1:3000/configure
3. No changes make and press Save button
Got error:
---
Can't locate object method "spurt" via package "/test2/Galileo-master/galileo.conf" (perhaps you forgot to load "/test2/Galileo-master/galileo.conf"?) at bin/../lib/Galileo/Command/setup.pm line 45, <DATA> line 38.
-- | --
40 | my %params = map { $_ => scalar $self->param($_) } @$names;
41 | foreach my $key ( qw/extra_css extra_js extra_static_paths secrets db_options pagedown_extra_options/ ) {
42 | $params{$key} = j($params{$key});
43 | }
44 |  
45 | $self->app->config_file->spurt($self->dumper(\%params));
46 |  
47 | $self->app->load_config;
48 | $self->humane_flash( 'Configuration saved' );
49 | $self->redirect_to('/');
50 | });
---

**Comment by jberger** [comment]
This appears that you are using a newer version of Mojolicious with an older version of Galileo. Galileo was fixed to support the new form of spurt in https://github.com/jberger/Galileo/commit/4820ebf4c74a5d97f727ed995759902075571abc . Please be sure you use Galileo 0.042 if you use Mojolicious version 7.31 or later.

**Comment by Bel-Kin** [comment]
$ mojo version
CORE
  Perl        (v5.22.1, linux)
  Mojolicious (6.15, Clinking Beer Mugs)

---

$ cat Changes 
Revision history for Perl module Galileo

0.042 2017-03-15
    - Fix use of deprecated Mojolicous functions
      - Bump Mojolicious requirement to 7.15

**Comment by jberger** [comment]
The changelog tells the story there. The requirement for Galileo 0.042 is Mojolicious 7.15. Your cpan install client should have updated Mojolicious for you when upgrading Galileo.

**Comment by Bel-Kin** [comment]
ok, thanks.
