### ISSUE TITLE
edit demo - lose "Fork me on GitHub" ribbon

### ISSUE THREAD

**Issue by ithgub** [jberger/Galileo#56]
After editing demo home page at [http://galileo-cms.herokuapp.com/page/home](http://galileo-cms.herokuapp.com/page/home), the top-right "Fork me on GitHub" ribbon got lost despite I didn't tamper with that string in the editor. The only thing I did was adding "Have fun" line at the end, this way:

```
Finally start your server

    galileo daemon

Have fun

<a href="https://github.com/jberger/Galileo"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png" alt="Fork me on GitHub"></a>
```

Inspecting page source revealed that `<img...>` tag was no longer present within `<a href...></a>`:

```
<p>Finally start your server</p>

<pre class="hljs"><code>galileo daemon
</code></pre>

<p>Have fun</p>

<p><a href="https://github.com/jberger/Galileo"></a></p>
</div>

    </div>
  </div>
</div>
</body>
</html>
```

**Comment by jberger** [comment]
As I now say in the documentation, this project and repository is discouraged. I'm not intending on maintaining it.
