### ISSUE TITLE
"Not saved! A title is required!" though title is present

### ISSUE THREAD

**Issue by ithgub** [jberger/Galileo#57]
On pressing "Save page" button while editing the demo home page at [http://galileo-cms.herokuapp.com/page/home](http://galileo-cms.herokuapp.com/page/home), I sometimes got a top-right popup
"Changes saved"
whereas sometimes
"Not saved! A title is required!"
appeared despite the original title was present.

**Comment by jberger** [comment]
As I now say in the documentation, this project and repository is discouraged. I'm not intending on maintaining it.
